#!/usr/bin/env python3

import os
import codecs
import markdown
import yaml
from jinja2 import Template

def files():
    f = []
    for (root, dirs, files) in os.walk("."):
        for file in files:
            f.append((os.path.join(root, file)))
    return f

def render(path):
    print(path)
    with codecs.open('page.html', mode="r", encoding="utf-8") as f:
        (head, tail) = f.read().split('---')
    with codecs.open(path, mode="r", encoding="utf-8") as f:
        (_, header, source) = f.read().split('---\n')
    meta = yaml.safe_load(header)
    body = markdown.markdown(source)
    template = Template(head + body + tail)
    html = template.render(meta)
    print(html)

def main():
    sources = [ p for p in files() if p.endswith('.md') ]
    for path in sources:
        render(path)

if __name__ == '__main__':
    main()
