#!/usr/bin/env python3

import os
import codecs
import markdown
import yaml

def files():
    f = []
    for (root, dirs, files) in os.walk("."):
        for file in files:
            f.append((os.path.join(root, file)))
    return f

def main():
    sources = [ p for p in files() if p.endswith('.md') ]
    for path in sources:
        render(path)

def render(path):
    print(path)
    with codecs.open(path, mode="r", encoding="utf-8") as f:
        text = f.read()
        (_, header, body) = text.split('---\n')
        meta = yaml.safe_load(header)
        print(meta)
        html = markdown.markdown(body)
        print(html)

if __name__ == '__main__':
    main()
